import { readdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Blog shells are generated by scripts/build-blog.js (npm run prebuild), so they
// are discovered from disk rather than listed by hand.
function blogInputs() {
  const dir = resolve(__dirname, 'blog');
  if (!existsSync(dir)) return {};
  return Object.fromEntries(
    readdirSync(dir)
      .filter((file) => file.endsWith('.html'))
      .map((file) => [`blog-${file.replace(/\.html$/, '')}`, resolve(dir, file)]),
  );
}

export default defineConfig({
  plugins: [react()],
  build: {
    target: 'es2019',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        growth: resolve(__dirname, 'growth.html'),
        connect: resolve(__dirname, 'connect.html'),
        blog: resolve(__dirname, 'blog.html'),
        ...blogInputs(),
      },
      output: {
        // Keep dependencies in one clearly-named shared chunk instead of letting
        // Rollup name it after whichever shared module it happened to see first.
        manualChunks(id) {
          if (id.includes('node_modules')) return 'vendor';
          return undefined;
        },
      },
    },
  },
});
